[package]
name = "pwebsyc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sycamore = "0.9.0-beta.1"
sycamore-router = "0.9.0-beta.1"

[workspace]
